version: '3.0'
services:
  rasa:
    build: .
    networks:
      - rasa-network
    depends_on:
      - action_server

  action_server:
    build: ./actions
    networks:
      - rasa-network

  socketio:
    build: ./socket-io
    ports:
      - 5000:5000
    networks:
      - rasa-network
    depends_on:
      - rasa

networks:
  rasa-network:
    driver: bridge
