version: '3.0'
services:
  rasa:
    image: 701428285404.dkr.ecr.ap-southeast-1.amazonaws.com/chainmart-chatbot-rasa:latest
    networks:
      - rasa-network
    depends_on:
      - action_server

  action_server:
    image: 701428285404.dkr.ecr.ap-southeast-1.amazonaws.com/chainmart-chatbot-action:latest
    networks:
      - rasa-network

  socketio:
    image: 701428285404.dkr.ecr.ap-southeast-1.amazonaws.com/chainmart-chatbot-socket.io:latest
    ports:
      - 5000:5000
    networks:
      - rasa-network
    depends_on:
      - rasa

networks:
  rasa-network:
    driver: bridge
